### ISSUE TITLE
Error trying to fetch data from iSeries DB2

### ISSUE THREAD

**Issue by jussihi** [soundstripe/iaccess#4]
* i Access Db2 SQLAlchemy Driver version: 0.6.0
* Python version: 3.11.8
* Operating System: Arch Linux
* iSeries OS: V7R3

### Description

Trying to connect to DB, errors out, below is a snippet:
```python
import sqlalchemy as db
from sqlalchemy import Engine
engine: Engine = db.create_engine('iaccess+pyodbc://sqluser:sqlpass@ipaddress/MYDB?DBQ=DEFAULT_SCHEMA')
connection = engine.connect()
metadata = db.MetaData()
mytable = db.Table('MYTABLE', metadata, autoload_with=engine)
query = db.select([mytable]).where(mytable.columns.MYCOL == '1240425')
ResultProxy = connection.execute(query)
ResultSet = ResultProxy.fetchall()
print(ResultSet)
```

results in error:
```
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', '[42S02] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0204 - Kirjaston SQLUSER *FILE-lajista objektia SYSCST ei lÃ¶ydy (-204) (SQLPrepare)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    mytable = db.Table('MYTABLE', metadata, autoload_with=engine)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __new__
  File ".venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 431, in __new__
    return cls._new(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 485, in _new
    with util.safe_reraise():
  File ".venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 481, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 861, in __init__
    self._autoload(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 893, in _autoload
    conn_insp.reflect_table(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 1526, in reflect_table
    _reflect_info = self._get_reflection_info(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 2009, in _get_reflection_info
    pk_constraint=run(self.get_multi_pk_constraint),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 1992, in run
    res = meth(filter_names=_fn, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 1008, in get_multi_pk_constraint
    return dict(
           ^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1096, in _default_multi_reflect
    single_tbl_method(
  File "<string>", line 2, in get_pk_constraint
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/iaccess/dialect.py", line 316, in get_pk_constraint
    r = connection.execute(s)
        ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
           ^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', '[42S02] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0204 - Kirjaston SQLUSER *FILE-lajista objektia SYSCST ei lÃ¶ydy (-204) (SQLPrepare)')
[SQL: SELECT "SYSCSTCOL"."CONSTRAINT_NAME", "SYSCSTCOL"."COLUMN_NAME"
FROM "SYSCST" JOIN "SYSCSTCOL" ON "SYSCST"."TABLE_SCHEMA" = "SYSCSTCOL"."TABLE_SCHEMA" AND "SYSCST"."TABLE_NAME" = "SYSCSTCOL"."TABLE_NAME" AND "SYSCST"."CONSTRAINT_NAME" = "SYSCSTCOL"."CONSTRAINT_NAME"
WHERE "SYSCST"."CONSTRAINT_TYPE" = ? AND "SYSCST"."TABLE_NAME" = ? AND "SYSCST"."TABLE_SCHEMA" = ?]
[parameters: ('PRIMARY KEY', 'MYTABLE', 'SQLUSER')]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

What am I doing wrong? :)

**Comment by soundstripe** [comment]
You're doing nothing wrong, but this library is not fully-featured yet, especially in the "reflection" capabilities.

To use this library effectively at the moment, you need to include your table definition in your Python code, either with SQLAlchemy "Core" or "ORM" code.

```python
import sqlalchemy as db
from sqlalchemy import Engine
engine: Engine = db.create_engine('iaccess+pyodbc://sqluser:sqlpass@ipaddress/MYDB?DBQ=DEFAULT_SCHEMA')
connection = engine.connect()
metadata = db.MetaData()
mytable = db.Table(    # remove the autoload_with param and define each column
  'MYTABLE', 
  metadata,
  db.Column('idcol', db.Integer, primary_key=True),
  db.Column('mycol', db.String(30)),
)
query = db.select([mytable]).where(mytable.columns.MYCOL == '1240425')
ResultProxy = connection.execute(query)
ResultSet = ResultProxy.fetchall()
print(ResultSet)
```

**Comment by jussihi** [comment]
@soundstripe thank you for the prompt response!

Can I ask you one more thing?

Let's say I have MYTABLE with those 2 columns defined by you, `idcol` and `mycol`. I have the code you defined above and it works fine.

Now I change the said table so that I add another column, let's say `thirdcol`. I will leave my code unchanged (it only has first two columns defined). Will the code break, since the table definition in my code is not 1-to-1 correct anymore?

**Comment by soundstripe** [comment]
The underlying table can have more columns than you describe in SQLAlchemy, so your code will still work (you just won't have access to those new/extra columns). 

At minimum, you must define a primary key that is actually unique across rows (and there are ways to use multi-column primary keys when necessary).
